groups:
    #- groupa
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: JARVIS
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - fantastical
