groups:
    #- groupa
recipes:
    mac_os_x:
        #- osxdefaults::use_dark_menu_bar_and_dock #broken for unknown reason
        - osxdefaults::set_computer_name
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::set_terminal_profile
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::disable_gatekeeper
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::tap_to_click
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_automatically_open_a_new_finder_window_when_a_volume_is_mounted
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_unhide_home
        - applications::sublime_text_3
        - applications::launchrocket
attributes:
    osxdefaults:
        computername: BigJARVIS
    authorization:
        sudo:
            users:
                - landonconover
            passwordless: true
            include_sudoers_d: true
    homebrewalt:
        apps:
            - git-extras
            - mongodb
        cask_apps:
            - fantastical
            - hyperdock
            - dropbox
            - google-drive
            - evernote
            - spotify
            - mou
            #- macfusion
            - firefox
            #- parallels-desktop
            #- navicat-for-mysql
            - steam
    sublime_text_packages:
        -
            name: GitGutter
            source: https://github.com/jisaacks/GitGutter.git
            branch: master
        -
            name: SCSS
            source: https://github.com/MarioRicalde/SCSS.tmbundle.git
            branch: SublimeText2
        -
            name: Theme - Spacegray
            source: https://github.com/kkga/spacegray.git
            branch: master
        -
            name: Emmet
            source: https://github.com/sergeche/emmet-sublime.git
            branch: master
    sublime_text:
        color_scheme: Packages/Theme - Spacegray/base16-eighties.dark.tmTheme
        preferences:
            theme: Spacegray Eighties.sublime-theme
    git:
        name: Landon Conover
        email: landon.conover@gmail.com
    nodejs:
        apps:
            - uglify-js
            - uglifycss
            - bower
            - grunt
            - grunt-cli
    gems:
        - sass
